### ISSUE TITLE
[EPIC] - Lib Contracts

### ISSUE THREAD

**Issue by WhiteAngel13** [infinity-js/lib-contracs#1]
## Description
- [ ] Initialize a npm package project
- [ ] Create a type Entity at `@infinity-js/contracts/entity`
- [ ] Create a BaseRepository type at `@infinity-js/contracts/repository`
- [ ] Implements testing environment
- [ ] Implements CI using testing threshold
- [ ] Implements CD to upload library at NPM
